name: TF Docs

on:
  workflow_call:
    inputs:
      path:
        type: string
        required: true
        description: "Path to the root directory of the Terraform module for which documentation will be generated"

jobs:
  generate-docs:
    runs-on: self-hosted
    container:
      image: ghcr.io/tinycloud-labs/tf-tools:latest

    steps:
      - uses: shakir85/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/setup-git
        with:
          repo-path: /__w/homelab/homelab

      - run: |
          git fetch origin ${{ github.head_ref }}
          git pull origin ${{ github.head_ref }}

      - name: Generate Terraform Docs Recursively
        run: |
          find terraform/catalog/modules/ -mindepth 2 -type f -name "main.tf" -exec dirname {} \; | while read dir; do
            echo "ðŸ“„ Generating docs for $dir"
            (cd "$dir" && terraform-docs markdown document .)
          done

      - name: Commit changes
        run: |
          git add -A
          git commit -m "ðŸ¤– chore: update Terraform docs [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
