name: Terragrunt Environment Deployment
run-name: Deploy Terragrunt ${{ github.event.inputs.environment }} Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy'
        required: true
        type: choice
        default: 'dev'
        options:
          - dev
          - prod

jobs:
  # Spin up VMs + provision K3s + cert-manager + GH Arc
  infra:
    uses: ./.github/workflows/callable-terragrunt.yml
    secrets: inherit
    with:
      module-path: terraform/live/${{ inputs.environment }}/infra

  # Wait for CRDs to register with the API Server. TODO: find a better approach.
  crd_warmup:
    needs: infra
    runs-on: controller
    steps:
      - name: Wait for K8s Operator CRDs to be ready
        run: sleep 300

  # Deploy tools that apps depend on
  platform:
    needs: crd_warmup
    uses: ./.github/workflows/callable-terragrunt.yml
    secrets: inherit
    with:
      module-path: terraform/live/${{ inputs.environment }}/platform
